### ISSUE TITLE
关于部分情况下KiyomiPDF查看中文PDF时无法正确显示标题的问题

### ISSUE THREAD

**Issue by lisp19** [qinlili23333/KiyomiPDF#1]
版本：1.0.5
手机环境：Android 12L，WebView已更新至最新
PDF文件来源：MacOS12.3.1下使用Typora默认导出
现象：手机端查看中文标题PDF时标题位置为空白，同一文件使用移动端word、Mac系统默认阅读器、Adobe Acrobat DC显示均正常
正常情况：
<img width="514" alt="Normal" src="https://user-images.githubusercontent.com/57988803/163677852-624f6615-a660-4b4c-b01f-7fb28e788ca0.png">
非正常情况：
![Abnormal](https://user-images.githubusercontent.com/57988803/163677860-0f09c389-0601-431b-9560-cea7ed21dafa.png)

**Comment by qinlili23333** [comment]
能提供下pdf文件么，我推测应该是字体fallback问题

**Comment by lisp19** [comment]
测试发现问题所用PDF文件已添加到邮件附件中。另外经过额外测试后发现：
1. 对于发现原问题所用PDF文件，问题可复现
2. 使用同样方法生成PDF后，问题有时不能复现。
推测原问题可能与我使用环境也有关联。
另附同一PDF文件使用安卓端word打开效果图如下




在 2022-04-17 09:49:06，"琴梨梨" ***@***.***> 写道：

能提供下pdf文件么，我推测应该是字体fallback问题

**Comment by lisp19** [comment]
> 能提供下pdf文件么，我推测应该是字体fallback问题

测试发现问题所用PDF文件已添加到附件中。另外经过额外测试后发现：
1. 对于发现原问题所用PDF文件，问题可复现
2. 使用同样方法生成PDF后，问题有时不能复现。

推测原问题可能与我使用环境也有关联。
另附同一PDF文件使用安卓端word打开效果图如下
![Word](https://user-images.githubusercontent.com/57988803/163700211-da480a5b-e226-4a3e-b7ef-1ee57d0a0476.png)
[TEST.pdf](https://github.com/qinlili23333/KiyomiPDF/files/8500976/TEST.pdf)

**Comment by qinlili23333** [comment]
确认是字体问题，你生成的PDF中文字体为Ping Fang Smallcaps，但你并未嵌入该字体到PDF，在大部分阅读器上这会导致fallback回系统字体，而KiyomiPDF对于未嵌入且系统内不存在的字体会直接选择不渲染。

**Comment by lisp19** [comment]
> 确认是字体问题，你生成的PDF中文字体为Ping Fang Smallcaps，但你并未嵌入该字体到PDF，在大部分阅读器上这会导致fallback回系统字体，而KiyomiPDF对于未嵌入且系统内不存在的字体会直接选择不渲染。

已收到回复，感谢解答。
