### ISSUE TITLE
无法打开本地文件

### ISSUE THREAD

**Issue by lampshe** [qinlili23333/KiyomiPDF#2]
你好，大神，非常感谢开发出这么小巧精致的pdf阅读器，因为自己的系统是鸿蒙4.2.0（官方说法是兼容安卓），但安装之后，即便给了访问文件权限，还是没有办法正常阅读pdf文档，界面是一片灰色，如果有时间，还请帮忙改进一下兼容性，多谢多谢！！

**Comment by qinlili23333** [comment]
我没有可用的设备进行调试，无法修复
